image: node:18

build: &build
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run generate
        artifacts:
          - .output/**
          
push: &push
  step:
      name: Deploy to Firebase
      deployment: production
      script:
        - pipe: atlassian/firebase-deploy:3.1.1
          variables:
            FIREBASE_TOKEN: $FIREBASE_TOKEN
            PROJECT_ID: $FIREBASE_STAGE_PROJECT
            PUBLIC_DIR: '.output/public'
            NODE_JS_VERSION: '18'

pipelines:
  default:
  - <<: *build
  - <<: *release-dev
  branches:
    develop:
    - <<: *build
    - <<: *push