image: node

pipelines:
  default:
    - step:
        name: Build
        script:
          - pnpm install && pnpm run build
        artifacts:
          - .output/public/**

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.2.1
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT